# Generated by Django 2.1.7 on 2019-02-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='userb',
            new_name='userblog',
        ),
    ]
