# Generated by Django 2.1.7 on 2019-02-25 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20190224_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Band')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='userblog',
        ),
        migrations.DeleteModel(
            name='Blogpost',
        ),
        migrations.DeleteModel(
            name='Userblog',
        ),
    ]
